### ISSUE TITLE
"About" description does not describe the project

### ISSUE THREAD

**Issue by LyndonGingerich** [taidalog/Fermata#26]
This project is listed in Sergey Tihon's F# Weekly newsletter like this:

[taidalog/Fermata: F# miscellaneous library](https://github.com/taidalog/Fermata)

Could the Fermata's About section be specified a bit more so viewers can see its purpose quickly?

**Comment by taidalog** [comment]
Thank you for opening an issue, @LyndonGingerich !
I've just visited the page you gave me the link to, and saw what other projects' About sections are like.
Does this explanation help you see its purpose: "Fermata: An F# library for working with values of basic types in F#. Compatible with Fable."?
It'd be nice if you would give me some advice. (I'm not an English speaker, and this is my first issue from someone.)

**Comment by LyndonGingerich** [comment]
So it's a library of helpers. Interesting.

Yes, that description is much more specific. Thanks!

**Comment by taidalog** [comment]
Yes, Fermata is a collection of helper functions I've written.
So I'll revise the About section just like:

An F# helper library for working with values of basic types in F#. Compatible with Fable.

Thank you for your comments!
